# Generated by Django 4.2.23 on 2025-09-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackpoint',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
