# Generated by Django 4.2.23 on 2025-09-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_trackpoint_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='calculated_elevation_gain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='calculated_length_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='external_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True, help_text='Persönliche Notizen zu dieser spezifischen Etappe.'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='manual_duration',
            field=models.DurationField(blank=True, help_text='Format: HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='manual_elevation_gain',
            field=models.IntegerField(blank=True, help_text='Höhenmeter im Aufstieg', null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='manual_length_km',
            field=models.FloatField(blank=True, help_text='Distanz in Kilometern', null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(help_text="z.B. 'Tag 1: Aufstieg zur Hütte'", max_length=200),
        ),
    ]
