# Generated by Django 4.2.23 on 2025-09-02 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stage_calculated_elevation_gain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
