# Generated by Django 4.2.23 on 2025-09-02 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stage_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='calculated_elevation_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, help_text='Persönliche Erinnerungen zum gesamten Trip.'),
        ),
        migrations.CreateModel(
            name='Hut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huts', to='api.trip')),
            ],
        ),
    ]
