# Generated by Django 4.2.23 on 2025-09-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stage_calculated_elevation_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='calculated_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
