# Generated by Django 4.2.23 on 2025-09-03 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_stage_calculated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='manual_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='manual_elevation_gain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='manual_length_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
