# Generated by Django 4.2.23 on 2025-09-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_stage_participants_alter_stage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='participants',
        ),
    ]
