# Generated by Django 4.2.23 on 2025-09-04 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_stage_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='timestamp',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='storage_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploader',
        ),
        migrations.AddField(
            model_name='photo',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='display',
            field=models.ImageField(default='', upload_to='photos/display/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='display_webp',
            field=models.ImageField(default='', upload_to='photos/display_webp/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='original',
            field=models.ImageField(default='', upload_to='photos/originals/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='photos/thumbnails/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_webp',
            field=models.ImageField(default='', upload_to='photos/thumbnails_webp/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, help_text='Optionale Bildbeschreibung', max_length=255),
        ),
    ]
