# Generated by Django 4.2.23 on 2025-09-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='original_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='original_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='original',
            field=models.ImageField(height_field='original_height', upload_to='photos/originals/', width_field='original_width'),
        ),
    ]
