# Generated by Django 4.2.23 on 2025-09-08 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_photo_original_height_photo_original_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='activity_type',
            field=models.CharField(choices=[('HIKING', 'Hiking'), ('RUNNING', 'Running'), ('SURFING', 'Surfing')], default='HIKING', max_length=10),
        ),
        migrations.AddField(
            model_name='stage',
            name='surf_spot',
            field=models.CharField(blank=True, help_text='Name or description of surf spot', max_length=200),
        ),
        migrations.AddField(
            model_name='stage',
            name='surfboard_used',
            field=models.CharField(blank=True, help_text='Type/description of surfboard', max_length=100),
        ),
        migrations.AddField(
            model_name='stage',
            name='tide_movement',
            field=models.CharField(blank=True, choices=[('RISING', 'Rising'), ('FALLING', 'Falling')], max_length=7),
        ),
        migrations.AddField(
            model_name='stage',
            name='tide_stage',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MID', 'Mid'), ('HIGH', 'High')], max_length=5),
        ),
        migrations.AddField(
            model_name='stage',
            name='time_in_water',
            field=models.DurationField(blank=True, help_text='Time spent surfing', null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='water_temperature',
            field=models.FloatField(blank=True, help_text='Water temperature in Celsius', null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='wave_height',
            field=models.FloatField(blank=True, help_text='Wave height in meters', null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='wave_quality',
            field=models.IntegerField(blank=True, help_text='Wave quality rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='stage',
            name='waves_caught',
            field=models.IntegerField(blank=True, help_text='Number of waves caught', null=True),
        ),
    ]
