# Generated by Django 4.2.23 on 2025-09-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_stage_activity_type_stage_surf_spot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='activity_type',
            field=models.CharField(choices=[('HIKING', 'Hiking'), ('RUNNING', 'Running'), ('SURFING', 'Surfing')], default='HIKING', max_length=10),
        ),
    ]
