# Generated by Django 4.2.23 on 2025-09-09 07:10

from django.db import migrations
from collections import Counter


def populate_trip_activity_type(apps, schema_editor):
    """
    Set trip activity_type based on the predominant activity of their stages.
    If stages are mixed or no stages exist, default to HIKING.
    """
    Trip = apps.get_model('api', 'Trip')
    Stage = apps.get_model('api', 'Stage')
    
    for trip in Trip.objects.all():
        # Get all stage activity types for this trip
        stage_activities = list(trip.stages.values_list('activity_type', flat=True))
        
        if stage_activities:
            # Find the most common activity type
            activity_counter = Counter(stage_activities)
            predominant_activity, _ = activity_counter.most_common(1)[0]
            trip.activity_type = predominant_activity
        else:
            # No stages, keep default HIKING
            trip.activity_type = 'HIKING'
        
        trip.save()


def reverse_populate_trip_activity_type(apps, schema_editor):
    """
    Reverse migration: reset all trips to HIKING (default)
    """
    Trip = apps.get_model('api', 'Trip')
    Trip.objects.update(activity_type='HIKING')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_trip_activity_type'),
    ]

    operations = [
        migrations.RunPython(populate_trip_activity_type, reverse_populate_trip_activity_type),
    ]
