# Generated by Django 4.2.23 on 2025-09-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20250909_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='activity_type',
            field=models.CharField(choices=[('HIKING', 'Hiking'), ('SURFING', 'Surfing')], default='HIKING', max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='activity_type',
            field=models.CharField(choices=[('HIKING', 'Hiking'), ('SURFING', 'Surfing')], default='HIKING', max_length=10),
        ),
    ]
