# Generated by Django 4.2.23 on 2025-09-09 09:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_running_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Country for surf trips', max_length=2),
        ),
    ]
