# Generated by Django 4.2.23 on 2025-09-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_trip_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='swell_direction',
            field=models.CharField(blank=True, choices=[('N', 'North'), ('NE', 'Northeast'), ('E', 'East'), ('SE', 'Southeast'), ('S', 'South'), ('SW', 'Southwest'), ('W', 'West'), ('NW', 'Northwest')], help_text='Primary swell direction', max_length=2),
        ),
        migrations.AddField(
            model_name='stage',
            name='wave_energy',
            field=models.FloatField(blank=True, help_text='Wave energy/power rating', null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('N', 'North'), ('NE', 'Northeast'), ('E', 'East'), ('SE', 'Southeast'), ('S', 'South'), ('SW', 'Southwest'), ('W', 'West'), ('NW', 'Northwest')], help_text='Wind direction', max_length=2),
        ),
    ]
