# Generated by Django 4.2.23 on 2025-09-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_stage_swell_direction_stage_wave_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_quick_user',
            field=models.BooleanField(default=False, help_text='User created quickly with just a name, without full account setup'),
        ),
    ]
