# Generated by Django 4.2.23 on 2025-09-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_is_quick_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='manual_elevation_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
