# Generated by Django 4.2.23 on 2025-10-01 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_stage_manual_elevation_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='surfboard_used',
            field=models.CharField(blank=True, help_text='Type/description of surfboard (legacy text field)', max_length=100),
        ),
        migrations.CreateModel(
            name='Surfboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 6'2 Shortboard, 9'0 Longboard", max_length=100)),
                ('board_type', models.CharField(choices=[('SHORTBOARD', 'Shortboard'), ('LONGBOARD', 'Longboard'), ('FISH', 'Fish'), ('FUNBOARD', 'Funboard'), ('GUN', 'Gun'), ('HYBRID', 'Hybrid'), ('FOAMBOARD', 'Foamboard'), ('OTHER', 'Other')], default='SHORTBOARD', max_length=20)),
                ('length', models.CharField(blank=True, help_text="e.g. 6'2, 190cm", max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surfboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='surfboard',
            field=models.ForeignKey(blank=True, help_text='Surfboard used in this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='api.surfboard'),
        ),
    ]
