# Generated by Django 4.2.23 on 2025-10-02 20:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_stage_surfboard_used_surfboard_stage_surfboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='surf_spot',
            field=models.CharField(blank=True, help_text='Name or description of surf spot (legacy text field)', max_length=200),
        ),
        migrations.AlterField(
            model_name='stage',
            name='tide_movement',
            field=models.CharField(blank=True, choices=[('RISING', 'Rising'), ('FALLING', 'Falling')], help_text='Tide direction during session', max_length=7),
        ),
        migrations.AlterField(
            model_name='stage',
            name='tide_stage',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MID', 'Mid'), ('HIGH', 'High')], help_text='Tide height during session', max_length=5),
        ),
        migrations.AlterField(
            model_name='stage',
            name='wave_quality',
            field=models.IntegerField(blank=True, help_text='Wave quality rating: 1=Poor, 2=Fair, 3=Good, 4=Great, 5=Epic', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='SurfSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Pipeline, Malibu, Supertubes', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surf_spots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='surf_spot_obj',
            field=models.ForeignKey(blank=True, help_text='Surf spot for this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='api.surfspot'),
        ),
    ]
