# Generated by Django 4.2.23 on 2025-10-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_stage_surf_spot_alter_stage_tide_movement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='crowd_factor',
            field=models.CharField(blank=True, choices=[('EMPTY', 'Empty'), ('CHILL', 'Chill'), ('CROWDED', 'Crowded'), ('PACKED', 'Packed')], help_text='How crowded was the surf spot', max_length=10),
        ),
    ]
