# Generated by Django 4.2.23 on 2025-10-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_stage_crowd_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='wind_speed',
            field=models.FloatField(blank=True, help_text='Wind speed in km/h', null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='wave_energy',
            field=models.FloatField(blank=True, help_text='Wave energy/power rating in kJ', null=True),
        ),
    ]
