# Generated by Django 4.2.23 on 2025-10-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_stage_wind_speed_alter_stage_wave_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='average_wait_time',
            field=models.IntegerField(blank=True, help_text='Average wait time per session in minutes (for riverwaves)', null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='environment',
            field=models.CharField(blank=True, choices=[('OCEAN', 'Ocean'), ('RIVERWAVE', 'Riverwave'), ('POOLWAVE', 'Poolwave')], default='OCEAN', help_text='Surf environment type (Ocean/Riverwave/Poolwave)', max_length=10),
        ),
        migrations.AddField(
            model_name='stage',
            name='flow_rate',
            field=models.FloatField(blank=True, help_text='Flow rate in m³/s (optional, for riverwaves)', null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='water_level',
            field=models.FloatField(blank=True, help_text='Water level in meters above sea level (optional, for riverwaves)', null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='wave_power',
            field=models.CharField(blank=True, choices=[('DEAD', 'Dead'), ('SOFT', 'Soft'), ('FUN', 'Fun'), ('JUICY', 'Juicy'), ('BEAST_MODE', 'Beast Mode')], help_text='Wave power rating for riverwaves', max_length=10),
        ),
    ]
